//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing
{
    using System;
    using System.Collections.Generic;
    
    public partial class chk_bill
    {
        public Nullable<System.DateTime> Receive_Date { get; set; }
        public string HN { get; set; }
        public string Receipt_No { get; set; }
        public string Name { get; set; }
        public Nullable<double> Net { get; set; }
        public string payer_name { get; set; }
        public string regis_name { get; set; }
        public string welfare_name { get; set; }
        public string AR { get; set; }
        public string Pending_delivery { get; set; }
        public string SAP_HN { get; set; }
        public Nullable<System.DateTime> Date_Scan { get; set; }
    }
}
